sudo: required
language: node_js
node_js:
- node
install:
- npm install
addons:
  sonarcloud:
    organization: carlsonorozco-github
    token:
      secure: YG5546qFhFGsFyqUqGbblnbTDahECuWyRSdpTiFTplvmmuoljsjCNGu30oYCEB3C8zCcvclaCgZ2NuzVOhTLJxk+M/GjzuC3am5luFiaKIDrMeE/iEiWeiKw8RrGWIfKt/NhTN7mw4AGmmr2+zDTEhC4iqqA8L3Xsy6T6mmDJLLibPqgXYJZEv0Hscfxs5ICATDKDT/16eFYftJZuH2FF6k7dBg9SYLaEarRoLmAkC+VSyqThVFyCwbFdWMRQsyZbqY+5VXIKaW1srxnAV60AGAiOoTfykx2EX5HUXtiwuOB2CDlEpJMh0DRJ0BJdQtS6nAXmNjdWsE5Asrel6UFsxS3ze2206xN+4ltjRjlG7OqjpPHS9NyhUMQOfi9Yi6MZfSg5mq3uB4qgHaJ9DB5s/0NS7+9d2GAnpduCWqWrm29iIhohw0YP466ACFZSWHEX8X3Ozz2bkIsJ/79Sc3rVgHjqrDuyGYBEG9azrbmP09pFBrkI6Er7dwa3WMSpxTmYFrkWPVJXqZgIX5I59ukhzLM5jQF++o4mqW8wrS8QZqXs+r870Z1WRozOqgZixK4WyvaIr9LysZvTDlMNGRsoIq8IMJEYsZH1HGPhWqa4VIbG94w25IG1mTaEREKB3mZQRTruQGiYUPfnVE+TIc+SoEIH7grmlkoqA9yzzt1c2k=
    github_token:
      secure: SxlrNXa+aoWBMraNUz7PVfo1u+Ha7kEPOIBMCKJknyqCqIaciRSnFIBFZApk+tun+5G5jNsL7g7xIsOm3/V5bePP2TMHMloMHBXAat/9SV1/9I+Lbn5B4pue43ghbbMWeeYHpd9rNan0dplgldSuJhNtLjfwcuGwIwqkvQl9ZWkrSbFT/GS6xJNBPZcO4ovFUQDyzAx7YbpR7q55zWlCpzLLWOllgzKqrqmePGfeAQ/5DMgfgaSSlSUS/TwvawSfEd1aY2ro4tdnBXXffEZU6+82S2fBSTiDKduHz6G/1dEBF8NTO3PdQjfi3TdnfxM4TkITanir7YEU9x29NpYhcOsUF2ndoDmqrUf7x+CedevoTGpXIoUKqeCr2uUXVG0w29c5IZITMwUVUSLVbibZ7yx7nKmsVa4ZRAii0uuch+tNAIEi3h4CohoS6mZGyu/M7mc5TfWG+pcdvNvCJYOdsT1fhNeLHKPv9zTKPgtKaFYeWsmeWkiqur3Tyc3TdH2hRMCph17Yj16674VP7f6GOzkxYoyb5TES0uMyEyf4YWw58j0GnUMJXUJ2yHbG5My3Hy+RN6wNHr3nBXcJ7OOu98ZHeSpSaXXCkFrNU8HK3fQESgcRrR3VO0zcCa1Q3O+FAAzpOG8OrVTYxnNw8v1SpnGIuBiUPn6fPeRPTMUD9+Y=
    branches:
    - master
    - develop
script:
- npm test
- sonar-scanner
cache:
  directories:
  - "$HOME/.sonar/cache"
env:
  matrix:
    secure: A65J7wQygOQGcBCtlvii7U3/Nj8fE3Iq1+4Tmpwc5CvaTCAx9bh/vp00XE/r65hzPRZzl/SzVzdQ0zgvRSppKPwbtnWwwSosjVkbNiz86AIViw/FBCDxMwjMJfDJJPJuK65xYriFBQ0bZ+46J6OwQ22BNo8b3uMInxusRqZW/2K6302P3wUkMHybwiC4HfhRO65vYTnBn/hkBhTjmURPzqnqYm0GQ/wyWyEV1ulO+fQ1kCEW/rDV+Ys1yTScevj4I+JNqagxDrWsAWsyZ4kBlUfq81feA19FhQXjBXnV8a832UcWVvS/7LgDNAz/9mM/iE3Pv9TqjUEDO4rgFjHCiC66eIO/TVhgCBghf/jGEWSjW3xlNVBeTZbVtiilRxNMv9bxdVm8cbnvAgJS7vYTGGTJc1H0qvuWvyEPDrCf1lvq8dTItxbf1TGZty6kievxtblSPhwri+Qi6eYkbbVjX6PptRLHoXpflXQpr0rr1E+lMJ7rw8LKe4J0hQ0pYbGFVz5jGpJrpU4gSsqDO9RQYN+svpFoXfBoaZsc+Zqj6M+7g9orqcWxGXY7Um2d8k2fL97uzLxrtBrkbRL4T0eThuRNzWosAmekn6oI5gIFhoG6RFqttp3tbHguERt5eT4XQbsNWF7JwbbFuZUXCr8v9tOKqCCXnrON0jrdj2sqwvw=
