sudo: required
language: node_js
node_js:
- node
install:
- npm install
addons:
  sonarcloud:
    organization: carlsonorozco-github
    token:
      secure: YG5546qFhFGsFyqUqGbblnbTDahECuWyRSdpTiFTplvmmuoljsjCNGu30oYCEB3C8zCcvclaCgZ2NuzVOhTLJxk+M/GjzuC3am5luFiaKIDrMeE/iEiWeiKw8RrGWIfKt/NhTN7mw4AGmmr2+zDTEhC4iqqA8L3Xsy6T6mmDJLLibPqgXYJZEv0Hscfxs5ICATDKDT/16eFYftJZuH2FF6k7dBg9SYLaEarRoLmAkC+VSyqThVFyCwbFdWMRQsyZbqY+5VXIKaW1srxnAV60AGAiOoTfykx2EX5HUXtiwuOB2CDlEpJMh0DRJ0BJdQtS6nAXmNjdWsE5Asrel6UFsxS3ze2206xN+4ltjRjlG7OqjpPHS9NyhUMQOfi9Yi6MZfSg5mq3uB4qgHaJ9DB5s/0NS7+9d2GAnpduCWqWrm29iIhohw0YP466ACFZSWHEX8X3Ozz2bkIsJ/79Sc3rVgHjqrDuyGYBEG9azrbmP09pFBrkI6Er7dwa3WMSpxTmYFrkWPVJXqZgIX5I59ukhzLM5jQF++o4mqW8wrS8QZqXs+r870Z1WRozOqgZixK4WyvaIr9LysZvTDlMNGRsoIq8IMJEYsZH1HGPhWqa4VIbG94w25IG1mTaEREKB3mZQRTruQGiYUPfnVE+TIc+SoEIH7grmlkoqA9yzzt1c2k=
    github_token:
      secure: SxlrNXa+aoWBMraNUz7PVfo1u+Ha7kEPOIBMCKJknyqCqIaciRSnFIBFZApk+tun+5G5jNsL7g7xIsOm3/V5bePP2TMHMloMHBXAat/9SV1/9I+Lbn5B4pue43ghbbMWeeYHpd9rNan0dplgldSuJhNtLjfwcuGwIwqkvQl9ZWkrSbFT/GS6xJNBPZcO4ovFUQDyzAx7YbpR7q55zWlCpzLLWOllgzKqrqmePGfeAQ/5DMgfgaSSlSUS/TwvawSfEd1aY2ro4tdnBXXffEZU6+82S2fBSTiDKduHz6G/1dEBF8NTO3PdQjfi3TdnfxM4TkITanir7YEU9x29NpYhcOsUF2ndoDmqrUf7x+CedevoTGpXIoUKqeCr2uUXVG0w29c5IZITMwUVUSLVbibZ7yx7nKmsVa4ZRAii0uuch+tNAIEi3h4CohoS6mZGyu/M7mc5TfWG+pcdvNvCJYOdsT1fhNeLHKPv9zTKPgtKaFYeWsmeWkiqur3Tyc3TdH2hRMCph17Yj16674VP7f6GOzkxYoyb5TES0uMyEyf4YWw58j0GnUMJXUJ2yHbG5My3Hy+RN6wNHr3nBXcJ7OOu98ZHeSpSaXXCkFrNU8HK3fQESgcRrR3VO0zcCa1Q3O+FAAzpOG8OrVTYxnNw8v1SpnGIuBiUPn6fPeRPTMUD9+Y=
    branches:
    - master
    - develop
script:
- npm test
- sonar-scanner
cache:
  directories:
  - "$HOME/.sonar/cache"
env:
  matrix:
    secure: FZ9JryGESd+Fn+FqD4JCmph+5neDT11PlEqrP23A4R9ujijzMnPXWmIgWmm3J6cdOqO7g9jqqnnBHOIc/DKof6q2PSIXlAKIH9v+6AnRdrSuE5vN5IkT/2yuBhARQmd0NhE4lU+CWUnpi90/4tgk1UArDnliYIkJeKftDMz/fRO8zZjsoI1MGnUqeJ1uX4CxLNQYn2Hh8V0EGPwQEustWEosbYVJ3fU5P5yF0pZ8NB2oFMZdzogIEr/8iuGET5fRooI4svGilws/+1g1EySbOSFeEDOrai2olXXWt6I+3QbzAVZ4XNMcIsMnnS3ddacC55F+bMd+5Km/5u/VR51t3yJxvqwTxCnX6fLZbprZZckkipmN8x9Knfm6YwmJLpuxEZWaM2eybQN/b+CdfoYtziPDwCjh6nQ2N/hZHXv2dljtlzVd8qaBBHzsYObR8W7FyBGP5/zBK+bl8jx9NCjHQrub0M2p8ruy+lnuepFdy/37LFtx528neq5ZLCZ2V/JZmg24PwR3AnQmiL1txzerQl6x8XQfBOb7Jx657tSdqvoWfi6YcLLdfS/9bwSvEeF5Fu3SQWPNt2hDGZXQ2n+W6ug6PtMhaMZeUP9ubiYjliT+T8Qnx3crxlTcCRxPgXz7WxgTPfR9PRcPmWPBr1eruVBlIlQMyYfgt+7QzM21akg=
